<div>
<a href="https://www.audiolabs-erlangen.de/fau/professor/mueller"><img src="data_layout/PCP_Teaser.png" width=100% style="float: right;" alt="PCP Teaser"></a>
</div>

# Unit 4: Basic Control Structures and Functions

<ul>
    <li><a href='#learn'>Overview and Learning Objectives</a></li>     
    <li><a href='#control'>Basic Control Structures</a></li>    
    <li><a href='#function'>Python Functions</a></li>  
    <li><a href='#runtime'>Efficiency and Runtime</a></li>     
    <li><a href='#exercise_give_number'>Exercise 1: Function <code>give_me_a_number</code></a></li>        
    <li><a href='#exercise_row_mean'>Exercise 2: Function for Computing Row Mean</code></a></li>
    <li><a href='#exercise_odd'>Exercise 3: Function for Computing Odd-Index Vector</a></li>
    <li><a href='#exercise_isprime'>Exercise 4: Primality Test</a></li>    
    <li><a href='#exercise_root'>Exercise 5: Function for Root Finding</a></li>         
</ul>

<a id='learn'></a> 
<div class="alert alert-block alert-warning">
<h2>Overview and Learning Objectives</h2>

This unit briefly introduces basic Python control structures (including `if`, `for`, and `while`),  which are similar to most other programming languages. Then, we look at how to create a function in Python using the keyword `def`. In particular, we discuss the difference between default and non-default arguments. Also, we give some guidelines on how to document a function using a suitable docstring. Finally, we show how one can measure the runtime for executing a function or small code snippets using the Python module `timeit`. In the first three exercises of this unit, you will implement some simple functions (which can be done in many ways) to familiarize yourself with the Python syntax. In <a href='#exercise_isprime'>Exercise 4</a>, we consider the mathematical problem of whether a natural number is a prime number. After implementing a simple Python function that solves this task, you should look for more efficient algorithms for primality testing. Going beyond the task specification, you may implement different algorithms and compare their runtime behavior and execution time for increasing numbers. Finally, in <a href='#exercise_root'>Exercise 5</a>, you find an accurate description of an algorithm for finding a root of a continuous function (i.e., an argument where the function assumes the value zero). While being a good exercise for implementing a mathematical procedure in executable Python code, this exercise also reviews some mathematical terms (e.g., interval, root, prime) that we think you should be familiar with. Furthermore, we want to make you aware that the notion of a function may appear in different contexts, e.g., once referring to a Python function and once to a mathematical function $f$ (which itself may serve as an argument to a Python function).
    
</div> 

<a id='control'></a>
## Basic Control Structures

In Python, there are basic control structures similar to most other programming languages. The most important control structures are:
<ul>
<li> <code>if</code>:  conditionally execute statements
<li> <code>for</code>:  repeat statements a specific number of times
<li> <code>while</code>:  repeat statements an indefinite number of times
<li> <code>break</code>:  terminate execution of a <code>while</code>  or <code>for</code>  loop
<li> <code>continue</code>:  continue execution of a <code>while</code>  or <code>for</code>  loop at top
</ul>

For control structures such as `if`, `for` or `while`, one has to use indentations (as part of the syntax). A typical Python convention is to use four spaces (or a tab indent). In the following, we give examples for each of these control structures. Let us start with an `if`-statement, which is written as follows:

In [1]:
n = -2
if n < 0:
    print('Negative')
elif n > 0:
    print('Positive')    
else:
    print('Zero')

Negative


The next example shows how to use a `for`-loop. Note that an iterable may be specified by a range, a list, a tuple, or even other structures.

In [2]:
for i in range(3):
    print(i, end='-')
print()
    
for i in ['a', 2, 'c', 'def']:
    print(i, end='-')
print()

for i in 'example':
    print(i, end='-')
print()

0-1-2-
a-2-c-def-
e-x-a-m-p-l-e-


A `while`-loop is written as follows:

In [3]:
a = 0
while a < 5:
    print(a, end='-')
    a += 1

0-1-2-3-4-

The `break`-statement is used to terminate the loop containing it. This is demonstrated by the following example, which consists of two nested loops each containing a  `break`-statement.

In [4]:
for k in 'abcd':
    if k == 'c':
        break
    for i in '12345':
        if i == '4':
            break
        print(k + i, end='-')

a1-a2-a3-b1-b2-b3-

The `continue`-statement is used to terminate only the current step of the loop. The loop then continues with the next iteration.

In [5]:
for k in 'abcd':
    if k == 'c':
        continue
    for i in '12345':
        if i == '4':
            continue
        print(k + i, end='-')

a1-a2-a3-a5-b1-b2-b3-b5-d1-d2-d3-d5-

<a id='function'></a>
## Python Functions

One defines functions with the `def`-keyword. As variable names, function names may contain letters (`a`, `b`, ..., `Y`, `Z`) and the underscore (`_`). All but the first character can also be positive integer number. Usually one uses lower case letters and underscores to separate words. The following function is named `add`. It has three arguments `a`, `b`, and `c` (with `b` and `c` having a default value). The `return` keyword is succeeded by the return value.

In [6]:
def add(a, b=0, c=0):
    """Function to add three numbers

    Notebook: PCP_04_control.ipynb

    Args:
        a: first number
        b: second number (Default value = 0)
        c: third number (Default value = 0)

    Returns:
        Sum of a, b and c
    """
    print('Addition: ', a, ' + ', b, ' + ', c)
    return a + b + c

print(add(5))
print(add(5, 2, 1))
print(add(5, c=4))

Addition:  5  +  0  +  0
5
Addition:  5  +  2  +  1
8
Addition:  5  +  0  +  4
9


There are some rules and differences on how to use arguments without and with default values. 

* All non-default arguments must be specified in the function call.
* The order of default arguments may not be changed in the call.
* The default arguments are optional in a call. If a value is provided, the default value is overwritten.
* A function may have any number of default arguments. However, a default argument may not be followed by a non-default argument. 

These rules are illustrated by the previous examples. The next example demonstrates that a function may also have multiple return values (which are returned as a tuple):

In [7]:
def add_and_diff(a, b=0):
    """Function to add and subtract two numbers

    Notebook: PCP_04_control.ipynb

    Args:
        a: first number
        b: second number (Default value = 0)

    Returns:
        first: a + b
        second: a - b
    """
    return a + b, a - b

x = add_and_diff(3, 5)
print('result:', x, type(x))
x, y = add_and_diff(3, 5)
print('result:', x, y, type(x), type(y))
x, y = add_and_diff(3.0, 5)
print('result:', x, y, type(x), type(y))

result: (8, -2) <class 'tuple'>
result: 8 -2 <class 'int'> <class 'int'>
result: 8.0 -2.0 <class 'float'> <class 'float'>


It is important to document a function. In particular, one should always describe the purpose of a function as well as its input and output. This is exactly what a **docstring** is used for. As described in the [Python Docstring Conventions](https://www.python.org/dev/peps/pep-0257/), a docstring is a string literal that occurs as the first statement in the function. For consistency, it is advised to use  `"""triple double quotes"""` around docstrings. Using the `help()` function, the content of the docstring is shown. This is a useful feature when building your own libraries with many functions. In the following code cell, we show the docstring of the function `add` defined above.

In [8]:
help(add)

Help on function add in module __main__:

add(a, b=0, c=0)
    Function to add three numbers

    Notebook: PCP_04_control.ipynb

    Args:
        a: first number
        b: second number (Default value = 0)
        c: third number (Default value = 0)

    Returns:
        Sum of a, b and c



<a id='runtime'></a>  
## Efficiency and Runtime

In the following example, we consider the task of computing the sum $\sum_{i=1}^n i$ for a given integer $n\in\mathbb{N}$. We first implement a naive function <code>sum_n</code> that uses a simple <code>for</code>-loop. We then execute the function <code>sum_n</code> in a <code>while</code>-loop for increasing $n=1,2,3,...$ and output the result until the sum exceeds $100$.</li>

In [9]:
def sum_n(n):
    """Function that sums up the integers from 1 to n

    Notebook: PCP_04_control.ipynb

    Args:
        n: Integer number

    Returns:
        s: Sum of integers from 1 to n
    """
    s = 0
    for n in range(1, n+1):
        s = s + n
    return s

n = 1
while sum_n(n) <= 100:
    print(f'n= {n}, s={sum_n(n)}')
    n += 1

n= 1, s=1
n= 2, s=3
n= 3, s=6
n= 4, s=10
n= 5, s=15
n= 6, s=21
n= 7, s=28
n= 8, s=36
n= 9, s=45
n= 10, s=55
n= 11, s=66
n= 12, s=78
n= 13, s=91


Rather than using a <code>for</code>-loop, one may think more efficient functions to compute this sum. In the following code cell, we consider the function <code>sum_n_numpy</code> that is based on the efficient NumPy-function <code>np.sum</code>. Furthermore, we consider the function <code>sum_n_math</code> which uses a closed mathematical formula for calculating the sum. We then measure and compare the execution time for the three different implementations. To this end, we use the Python module [<code>timeit</code>](https://docs.python.org/2/library/timeit.html), which provides a simple way to measure the execution time of small bits of Python code. As an alternative, one may also use the function <code>time.time()</code> of the module [<code>time</code>](https://docs.python.org/3/library/time.html).


In [10]:
import numpy as np

def sum_n_numpy(n):
    """Function that sums up the integers from 1 to n  using numpy

    Notebook: PCP_04_control.ipynb

    Args:
        n: Integer number

    Returns:
        s: Sum of integers from 1 to n
    """
    s = np.sum(np.arange(1, n+1))
    return s    

def sum_n_math(n):
    """Function that sums up the integers from 1 to n using the idea by Gauss

    Notebook: PCP_04_control.ipynb

    Args:
        n: Integer number

    Returns:
        s: Sum of integers from 1 to n
    """
    s = n * (n + 1) // 2
    return s   

n = 1000
print(f'Computation with sum_n:       n={n}, s={sum_n(n)}')
print(f'Computation with sum_n_numpy: n={n}, s={sum_n_numpy(n)}')
print(f'Computation with sum_n_math:  n={n}, s={sum_n_math(n)}')

# Measuring runtime of different implementations 
import timeit
executions = 100
n = 10000
runtime_av = timeit.timeit(lambda: sum_n(n), number=executions) / executions
print(f'Runtime for sum_n: {runtime_av * 1000:.6f} ms')

runtime_av = timeit.timeit(lambda: sum_n_numpy(n), number=executions) / executions
print(f'Runtime for sum_n_numpy: {runtime_av * 1000:.6f} ms')

runtime_av = timeit.timeit(lambda: sum_n_math(n), number=executions) / executions
print(f'Runtime for sum_n_math: {runtime_av * 1000:.6f} ms')

Computation with sum_n:       n=1000, s=500500
Computation with sum_n_numpy: n=1000, s=500500
Computation with sum_n_math:  n=1000, s=500500
Runtime for sum_n: 0.349630 ms
Runtime for sum_n_numpy: 0.004423 ms
Runtime for sum_n_math: 0.000080 ms


<div class="alert alert-block alert-warning">
<strong>Note:</strong> In Python programming, one can use the concept of lambda expressions when an anonymous one-line function is needed temporarily in a specific setting. Such a function takes the form <code>lambda args: expression</code>, where the expression is executed and the result is returned. For more details we refer to the <a href="https://docs.python.org/3/reference/expressions.html">Python Documentation</a>.
</div>

## Exercises and Results

In [1]:
import libpcp.control
show_result = True

<a id='exercise_give_number'></a>
<div class="alert alert-block alert-info">
<strong>Exercise 1: Function <code>give_me_a_number</code></strong><br>
Write a function <code>give_me_a_number</code> that has a string variable <code>s</code> as input argument. When <code>s</code> is the string <code>'large'</code>, the function should return the value $2^{100}$. If <code>s</code> is <code>'small'</code>, it should return $2^{-100}$. If <code>s</code> is <code>'random'</code>, it should return a random number in the range $[0,1)$ (using <code>np.random.rand</code>). In all other cases, the function should return <code>np.nan</code>. As default, set the input argument to the string <code>'nan'</code>.
</div>

In [20]:
#<solution>
import numpy as np
def give_me_a_number(s="nan"):
    if s == "large":
        return 2**100
    elif s == "small":
        return 2**-100
    elif s == "random":
        return np.random.rand()
    else:
        return np.nan

give_me_a_number("random")
print(f"default: {give_me_a_number()}")
print(f"s='large': {give_me_a_number("large")}")
print(f"s='small': {give_me_a_number("small")}")
print(f"s='random': {give_me_a_number("random")}")
print(f"s='test': {give_me_a_number("test")}")

#</solution>

default: nan
s='large': 1267650600228229401496703205376
s='small': 7.888609052210118e-31
s='random': 0.9706632355160714
s='test': nan


In [13]:
libpcp.control.exercise_give_number(show_result=show_result)

default:    nan
s='large':  1267650600228229401496703205376
s='small':  7.888609052210118e-31


s='random': 0.8589813666212172
s='test':   nan


<a id='exercise_row_mean'></a>
<div class="alert alert-block alert-info">
<strong>Exercise 2: Function for Computing Row Mean</strong><br>
Write a function <code>row_mean</code> that inputs a matrix and outputs a vector containing the row-wise means (averages) of the input matrix. Apply the function to the matrix matrix $\mathbf{A} = \begin{bmatrix}1 & 2 & 6 \\5 & 5 & 2\\\end{bmatrix}$.
</div>

In [33]:
#<solution>
def row_mean(matrix: np.array):

    return matrix.mean(1)

row_mean(np.array([[1, 2, 6], 
                   [5, 5, 2]]))
#</solution>

array([3., 4.])

In [15]:
libpcp.control.exercise_row_mean(show_result=show_result)

Input matrix:
[[1 2 6]
 [5 5 2]]
Vector containing the row means:  [3. 4.]


<a id='exercise_odd'></a>
<div class="alert alert-block alert-info">
<strong>Exercise 3: Function for Computing Odd-Index Vector</strong><br>
Given a vector <code>x</code> (in form of a one-dimensional NumPy array), write a function <code>vector_odd_index</code> that outputs a vector <code>y</code> consisting only of the elements of <code>x</code> at an odd index position. If the input NumPy array <code>x</code> is not a vector, the function <code>vector_odd_index</code> should output <code>y=None</code>. <br>
<strong>Note:</strong> Recall that Python indexing starts with index <code>0</code> (which is an even index).
</div>

In [80]:
#<solution>
def vector_odd_index(x: np.array):
    y = None
    if not isinstance(x, np.ndarray) or x.ndim != 1:
        return y
    y = x[1::2]
    return y
    

vector_odd_index(np.array([0, 3, 2, 5]))
#</solution>

array([3, 5])

In [75]:
x = np.array([1, 3, 5, 3])
type(x)


numpy.ndarray

In [17]:
libpcp.control.exercise_odd(show_result=show_result)

x = [0 1 2 3 4 5 6 7 8 9]
y = [1 3 5 7 9]
x = [[0 1 2 3 4 5 6 7 8 9]]
y = None
x =
[[1 2 3]
 [4 5 6]]
y = None


<a id='exercise_isprime'></a>
<div class="alert alert-block alert-info">
<strong>Exercise 4: Primality Test</strong><br>
An integer $n\in\mathbb{N}$ is called a <strong>prime number</strong> if $n>1$ and if $n$ is divisible only by $1$ and itself. Write a function <code>isprime</code> that inputs an integer <code>n</code> and outputs the boolean value <code>True</code> if <code>n</code> is a prime number and <code>False</code> otherwise. 
<ul>
<li> Test your function for $n=1$, $n=17$, $n=1221$, and $n=1223$.</li> 
<li> Use this function to output the first $20$ prime numbers. </li> 
<li> Discuss efficiency issues. Is there a more efficient way to compute the first $20$ prime numbers?</li>
<li> Have a look at the algorithm <a href="https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes"><strong>Sieve of Eratosthenes</strong></a>, which is an ancient algorithm for finding all prime numbers up to any given limit.</li>        
</ul>      
</div>

In [ ]:
#<solution>

def isprime(n):

    if n <= 1:
        return False
    if n == 2:
        return True
    if n % 2 == 0:
        return False

    for i in range(3, int(n**0.5) + 1, 2): # ???
        if n % i == 0:
            return False

    return True

for i in range(51):
    print(isprime(i))

#</solution>

In [132]:
#<solution>

def isprime(n):
    isPrime = True
    if n < 2:
        return False

    for i in range(2, n, 1):

        if n % i == 0:
            return False


    print(n)
    return isPrime


for num in range(72):
    isprime(num)
#</solution>

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71


In [19]:
libpcp.control.exercise_isprime(show_result=show_result)

n = 1, isprime = False
n = 17, isprime = True
n = 1221, isprime = False
n = 1223, isprime = True
List of first 20 prime numbers:
2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 

<a id='exercise_root'></a>
<div class="alert alert-block alert-info">
<strong>Exercise 5: Function for Root Finding</strong><br>
Let $f:\mathbb{R}\to\mathbb{R}$ be a continuous function and let $a,b\in\mathbb{R}$ be two numbers such that $a<b$ and $f(a)$ and $f(b)$ have opposite signs. Then $f$ has a <strong>root</strong> in the interval $[a,b]$. In other words, there is a number $r\in[a,b]$ such that $f(r)=0$. To find such a root, one can proceed as follows: 
<ul>
<li> Let $c = (a+b)/2$ be the center. If $f(a)=0$, $f(b)=0$, or $f(c)=0$, then we have found a root and we can stop. </li> 
<li> Otherwise, either $f(a)$ and $f(c)$, or $f(c)$ and $f(b)$ have opposite signs. In the first case, continue with the interval $[a,c]$, otherwise with the interval $[c,b]$.</li> 
<li> Iterate this interval-halving procedure until the interval size is below a given threshold parameter (e.g., $10^{-5}$) and a sufficient approximation for the root is obtained.</li>
</ul>  
    
Write a function <code>search_root</code> that implements this procedure (also known as <strong>bisection method</strong>). The input arguments should be <code>f</code>, <code>a</code>, <code>b</code>, and <code>thresh</code>. Here, <code>f</code> is a Python function realizing a continuous function $f:\mathbb{R}\to\mathbb{R}$. The parameter <code>thresh</code> is the threshold parameter, which should be set to the value $10^{-5}$ by default. The function <code>search_root</code> should check if <code>a < b</code> and if the opposite sign condition for <code>f(a)</code> and <code>f(b)</code> is fulfilled (if not it should return the value <code>np.nan</code>). 

<ul>
<li> Evaluate <code>search_root</code> for <code>f</code> given by $f(x) = x^2-2$, <code>a=0</code>, and <code>b=2</code>. <br>(Note: You may define a separate Python function <code>f</code> that implements  $f(x) = x^2-2$. This function can then be used as one of the input argument to the Python function <code>search_root</code>.)</li> 
<li> Test <code>search_root</code> for the same function when using <code>a=2</code> and <code>b=4</code>.  </li>  
<li> Test <code>search_root</code> for the same function when using <code>a=4</code> and <code>b=2</code>.  </li>    
<li> Evaluate <code>search_root</code> for <code>f</code> being <code>np.sin</code> using <code>a=3</code> and <code>b=4</code>. </li> 
</ul>
</div>

<div class="alert alert-block alert-warning">
<strong>Note:</strong> In this exercise, we draw attention to the fact that the argument of a Python function (e.g., <code>search_root</code>) can be a function itself (e.g., <code>f</code>). In Python, a function is simply an object that can be referred to in the same way one refers to a number, a string, or a list. For further explanations, we refer to the article on <a href="https://treyhunner.com/2020/01/passing-functions-as-arguments/">Passing a function as an argument to another function in Python</a>.  
</div>

In [7]:
import numpy as np
def f(x):

    return x**2 - 2

def search_root(f, a, b, thresh=10**-5):

    c = (a + b) / 2

    if a > b or np.sign(f(a)) == np.sign(f(b)):
        return np.nan

    elif (b - a) / 2 < thresh or f(c) == 0:
        return c
    
    elif np.sign(f(a)) != np.sign(f(c)):
        return search_root(f, a, c, thresh)

    elif np.sign(f(c)) != np.sign(f(b)):
        return search_root(f, c, b, thresh)

    return c

search_root(f=np.sin, a=3, b=4, thresh=10**-5)



3.1415939331054688

In [152]:
#<solution>


def search_root(f, a, b, thresh=10**-5):


    if a >= b or np.sign(f(a)) == np.sign(f(b)):
        return np.nan

    c = (a+b) / 2

    if (b-a) / 2 < thresh or f(c) == 0:

        return c

    if np.sign(f(a)) != np.sign(f(c)):

        return search_root(f, a, c, thresh)

    elif np.sign(f(c)) != np.sign(f(b)):
        
        return search_root(f, c, b, thresh)

root = search_root(f=lambda x: x**2 - 2, a=0, b=2)

print(f"========== Function f(x) = x**2 - 2 =============")
print(root)
#</solution>

========== Function f(x) = x**2 - 2 =============
1.4142074584960938


In [8]:
import numpy as np
def search_root(f, a, b, thresh=10**-5):

    c = (a+b) / 2 

    if a > b or np.sign(f(a)) == np.sign(f(b)):
        return np.nan


    if (b - a) / 2 < thresh or f(c) == 0:

        return c 

    elif np.sign(f(a)) != np.sign(f(c)):
        return search_root(f, a, c, thresh)

    elif np.sign(f(c)) != np.sign(f(b)):
        return search_root(f, c, b, thresh)


search_root(lambda x: x**2 - 2, 0, 2)



1.4142074584960938

In [21]:
libpcp.control.exercise_root(show_result=show_result)

=== Function f(x) = x**2-2 ===
a = 0.000000, b = 2.000000, c = 1.000000, f(a) = -2.000000, f(b) = 2.000000, f(c) = -1.000000
a = 1.000000, b = 2.000000, c = 1.500000, f(a) = -1.000000, f(b) = 2.000000, f(c) = 0.250000
a = 1.000000, b = 1.500000, c = 1.250000, f(a) = -1.000000, f(b) = 0.250000, f(c) = -0.437500
a = 1.250000, b = 1.500000, c = 1.375000, f(a) = -0.437500, f(b) = 0.250000, f(c) = -0.109375
a = 1.375000, b = 1.500000, c = 1.437500, f(a) = -0.109375, f(b) = 0.250000, f(c) = 0.066406
a = 1.375000, b = 1.437500, c = 1.406250, f(a) = -0.109375, f(b) = 0.066406, f(c) = -0.022461
a = 1.406250, b = 1.437500, c = 1.421875, f(a) = -0.022461, f(b) = 0.066406, f(c) = 0.021729
a = 1.406250, b = 1.421875, c = 1.414062, f(a) = -0.022461, f(b) = 0.021729, f(c) = -0.000427
a = 1.414062, b = 1.421875, c = 1.417969, f(a) = -0.000427, f(b) = 0.021729, f(c) = 0.010635
a = 1.414062, b = 1.417969, c = 1.416016, f(a) = -0.000427, f(b) = 0.010635, f(c) = 0.005100
a = 1.414062, b = 1.416016, c = 1.

<div>
<a href="https://opensource.org/licenses/MIT"><img src="data_layout/PCP_License.png" width=100% style="float: right;" alt="PCP License"></a>
</div>